server:
  port: 8082

spring: 
  application:
    name: user-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: "postgres"
    password: "2213"
  jpa:
    generate-ddl: false